### ISSUE TITLE
Issues validating UTF-8

### ISSUE THREAD

**Issue by cmkilger** [ldthomas/apg-py#1]
I'd like to use this project to validate some input using our ABNF, but it's having issues with any UTF-8 that's greater than a single byte. It looks like it's has something to do with the way you handle Unicode. Maybe you have a different approach than what I'm doing.

Part of the ABNF ensures that UTF-8 text is properly XML escaped.

```abnf
xml-text        = 1*(unencoded / encoded)
unencoded       = %x09 /
                  %x0A /
                  %x0D /
                  %x20-21 /
                     ; omit 0x22 double quote
                  %x23-25 /
                     ; omit 0x26 ampersand
                     ; omit 0x27 single quote
                  %x28-3B /
                     ; omit 0x3C less than
                  %x3D /
                     ; omit 0x3E greater than
                  %x3F-7E /
                  UTF8-2 /
                  UTF8-3 /
                  UTF8-4
encoded         = %x26 (%s"quot" / %s"amp" / %s"apos" / %s"lt" / %s"gt") %x3B
UTF8-2          = %xC2-DF UTF8-tail
UTF8-3          = %xE0 %xA0-BF UTF8-tail / %xE1-EC 2(UTF8-tail) /
                  %xED %x80-9F UTF8-tail / %xEE-EF 2(UTF8-tail)
UTF8-4          = %xF0 %x90-BF 2(UTF8-tail) / %xF1-F3 3(UTF8-tail) /
                  %xF4 %x80-8F 2(UTF8-tail)
UTF8-tail       = %x80-BF

```

Validation script:
```python
#!/usr/bin/env python3
from apg_py.lib import utilities as utils
from apg_py.lib.parser import Parser
from apg_py.api.api import Api
import sys
with open(sys.argv[1]) as f:
    grammar = f.read()
with open(sys.argv[2]) as f:
    input = f.read()
result = Parser(Api().generate(grammar)).parse(utils.string_to_tuple(input))
print(result.success)
```

Some small tests:
| input | expected | actual |
|--------|--------|--------|
| `Hello` | Pass | Pass |
| `G'day` | Fail | Fail |
| `G&apos;day` | Pass | Pass |
| `G’day` | Pass | Fail |
| `Adiós` | Pass | Fail |

**Comment by cmkilger** [comment]
Replacing `string_to_tuple`'s for loop with this works for me, but I don't know what side-effects that would have for the rest of the project.

```python
    for c in string.encode():
        lst.append(c)
```

**Comment by cmkilger** [comment]
I figured out how to fix the ABNF. I wasn't aware I could use `%x` to express a large Unicode value.

```ABNF
xml-text        = 1*(unencoded / encoded)
unencoded       = %x09 /
                  %x0A /
                  %x0D /
                  %x20-21 /
                     ; omit 0x22 double quote
                  %x23-25 /
                     ; omit 0x26 ampersand
                     ; omit 0x27 single quote
                  %x28-3B /
                     ; omit 0x3C less than
                  %x3D /
                     ; omit 0x3E greater than
                  %x3F-10FFFD
encoded         = %x26 (%s"quot" / %s"amp" / %s"apos" / %s"lt" / %s"gt") %x3B
```

**Comment by ldthomas** [comment]
Thanks for using apg-py. Good to see that you solved your own problem. Just a couple of comments.

First about ABNF. %b, %d and %x can all be used to represent any positive integer from 0 to sys.maxsize(). They have no relation to Unicode.

Second, if your XML encoding is UTF-32, as it seems to be here, you might want to exclude the surrogate pair range, as they are not valid Unicode code points by themselves. i.e replace
>%x3F-10FFFD
with
>%x3F-DFFF / %xE000-10FFFD

Just a suggestion. Good luck with your project.

**Comment by cmkilger** [comment]
Thanks. I'm actually using UTF-8. I was under the impression that the %x would only match a byte, but that doesn't appear to be the case. `string_to_tuple` is converting each character into its Unicode integer value which is what it's actually matching against, right? So, as I understand it, the original encoding shouldn't matter. (I'm really no Python expert either.)

Quoting the documentation for [ord()](https://docs.python.org/3/library/functions.html#ord).

> Given a string representing one Unicode character, return an integer representing the Unicode code point of that character. For example, ord('a') returns the integer 97 and ord('€') (Euro sign) returns 8364. This is the inverse of [chr()](https://docs.python.org/3/library/functions.html#chr).

**Comment by ldthomas** [comment]
ABNF rules define phrases simply as arrays of integers. It is up to the user to interpret the meaning of those integers. Since here the phrases are usually Python strings `string_to_tuple()` and `tuple_to_string()` are convenience functions to make those conversions between the strings and the arrays of integers that apg-py understands. So yes, the encoding that Python uses internally for strings doesn’t concern us. As far as your application goes, I’ll leave that to you and retract my comments there. I hope apg-py is a helpful tool for you.
